### ISSUE TITLE
test_parse_date_string fails comparing offset-naive and offset-aware types

### ISSUE THREAD

**Issue by lindauer** [akoumjian/datefinder#8] opened 2016-02-16 16:53 UTC
```
>           assert actual_datetime == expected_date
E           TypeError: can't compare offset-naive and offset-aware datetimes

tests/test_parse_date_string.py:61: TypeError
----------------------------- Captured stdout call -----------------------------
DEBUG:tests.test_parse_date_string:acutal=2015-11-20 18:00:00-06:00  expected=2015-11-20 18:00:00
```

It looks like the problem is test test itself, unless I misunderstand what is supposed to be happening.

```
diff --git a/tests/test_parse_date_string.py b/tests/test_parse_date_string.py
index 68e8e6b..eee6366 100644
--- a/tests/test_parse_date_string.py
+++ b/tests/test_parse_date_string.py
@@ -41,7 +41,7 @@ logger = logging.getLogger(__name__)
     (' on 11-20-2015 6pm CST ',
      '11-20-2015 6pm',
      {'timezones':['CST']},
-     datetime(2015, 11, 20, 18, 0)
+     datetime(2015, 11, 20, 18, 0).replace(tzinfo=tz.gettz('CST'))
     ),
     # test a tz abbreviation that
     # dateutile.tz.gettz cannot find
@@ -49,7 +49,7 @@ logger = logging.getLogger(__name__)
     (' on 11-20-2015 6am IRST ',
      '11-20-2015 6am',
      {'timezones':['IRST']},
-     datetime(2015, 11, 20, 6, 0)
+     datetime(2015, 11, 20, 6, 0).replace(tzinfo=tz.gettz('IRST'))
     )
 ])
 def test_parse_date_string_find_replace(date_string, expected_parse_arg, expected_captures, expected_date):
```

**Comment by akoumjian** [comment] 2016-02-17 02:44
@thebigspoon care to elaborate?

**Comment by thebigspoon** [comment] 2016-02-17 04:03
@lindauer: Yummy! 
Could you tell me what operating system you are on?
Could you also run the following commands in a Python shell with an environment that has `python-dateutil` installed? Let me know what gets returned please:
```python
In [23]: import dateutil
In [24]: dateutil.tz.gettz('IRST')
```

### breakdown
Yes, the problem is the test and probably the assumption that the operating system the test is running on doesn't have zoneinfo for the [timezone abbreviation -- IRST](http://www.timeanddate.com/time/zones/irst). Good catch!

`dateutil.tz.gettz` is basically a big `if/else` booby trap hunting for the right timezone files ( [here](https://github.com/dateutil/dateutil/blob/master/dateutil/tz/tz.py#L932-L937) ). On Ubuntu 14.04 it is looking to resolve `IRST` at this location:
```python
In [22]: ls -lah /usr/share/zoneinfo/I*
-rw-r--r-- 1 root root 1.2K Jun 13  2014 /usr/share/zoneinfo/Iceland
-rw-r--r-- 1 root root 1.7K Jun 13  2014 /usr/share/zoneinfo/Iran
-rw-r--r-- 1 root root 2.2K Jun 13  2014 /usr/share/zoneinfo/Israel
```
It doesn't find it and therefore tries to replace the tzinfo with `None` which mean it returns a naive datetime ( [here](https://github.com/akoumjian/datefinder/blob/master/datefinder.py#L185-L186) ) as the test was designed.

My guess is that the `dateutil.tz.gettz` lookup resolves for you and returns legitimate tzinfo. 

The test should probably use a really really wrong timezone abbreviation such as `NOT_A_TIMEZONE` ;-)

**Comment by lindauer** [comment] 2016-02-17 04:15
It actually returns None for me, too. Upon closer examination, I think it's the CST test failing, not the IRST test. I'm on OSX 10.10.5.

**Comment by thebigspoon** [comment] 2016-02-17 04:17
@lindauer:
so this does return something for you?
```python
In [23]: import dateutil
In [24]: dateutil.tz.gettz('CST')
```

**Comment by lindauer** [comment] 2016-02-17 04:28
It does!

```
>>> import dateutil.tz
>>> dateutil.tz.gettz('CST')
tzlocal()
```

**Comment by thebigspoon** [comment] 2016-02-18 15:36
@lindauer: thanks for sticking with this. I was able to reproduce the recurring issue you mention in PR #12 on OSX. For some reason the mock was not taking in the environment of OSX and anaconda. It's was working fine on Ubuntu and CentOS. 

So I've adjusted the mock in PR #13. If you could merge that PR locally and test it out I'd really appreciate it.

**Comment by thebigspoon** [comment] 2016-02-18 16:17
works, see notes on PR #13. closing

**Closed by thebigspoon** 2016-02-18 16:17 UTC
