### ISSUE TITLE
Issue with datefinder module python

### ISSUE THREAD

**Issue by Balaji001** [akoumjian/datefinder#29] opened 2016-09-30 11:28 UTC
I have used date finder module to read unformatted  dates, it is working great for some formats but when i read **from 21st Oct 2012 to 30/11/2012**  it is not giving proper dates. 
Expected:- 2012-10-21 00:00:00 and 2012-11-30 00:00:00 but i am getting following dates
2262-08-19 19:14:50, 2016-12-30 00:00:00

But when i removed **to** from above highlighted section it is giving proper dates. it will be great if any one solves this issue.

**Comment by akoumjian** [comment] 2016-09-30 14:46
Yes, this is a duplicate of #18 . Hopefully I can get to this in the upcoming week! Very open to PRs.

**Closed by akoumjian** 2016-09-30 14:46 UTC
