### ISSUE TITLE
Wrong Interpretation with "to" in string

### ISSUE THREAD

**Issue by ankitjain2604** [akoumjian/datefinder#25] opened 2016-08-26 11:56 UTC
For string "transactions from 14 Aug 2016 to 18 Aug 2016." the result is "no dates found". If I replace "to" with "till", it gives the correct result.

**Comment by akoumjian** [comment] 2016-08-29 15:31
Thanks for the feedback. We're working on this, but it is going to require a refactor. Duplicate of #18

**Closed by akoumjian** 2016-08-29 15:31 UTC
